### ISSUE TITLE
The Front Page Doesn't Scroll

### ISSUE THREAD

**Issue by Gerst20051** [Priyank1504/Passport_Inc_#1]
For small devices, the "Step In" button on the front page is not visible so users won't be able to continue past that screen.

**Comment by Priyank1504** [comment]
Hey Andy,


I apologize for the issue. I didn't get any small screen phone to test my app that time. Although, I took care different SDK versions that app can run on.
I just commit the file and included scrolling and small text sizes. 
Try running it again. Sorry, for the issue. 

Let me know if its working fine for you now?

Thanks for the cooperation!

**Comment by Gerst20051** [comment]
Yes, it works now thanks! Though now it's small enough that it doesn't need to scroll.

**Comment by Gerst20051** [comment]
~The car is also now showing up in front of the scrolling landscape instead of below the landscape.~ Disregard that it was always in front of the landscape.

**Comment by Priyank1504** [comment]
Yes, it will not get scroll down until the content exceeds the screen. For the safer side I put the scrollView.

Also, I'm guessing all floating buttons will might not be visible to select as I believe you are using the screen size below than or 5ish. Let me know if you get that isuue. I'll get it correct for you.

I test the app for the screen-size above 5ish that was the only availability I had that time. If its possible. Please try to run it on the bigger screen-size to get the whole picture.

Once again sorry for the inconvenience!
